var canvas = new Canvas();
canvas.createWithFatherNameAndPosition("fatherDiv",0,0,1000,1000,-1);
//var texture = new Texture();
//texture.create(canvas,"../asset/texture/test1.jpg",null);
//texture.loadTexture();
//texture.fixSizeAsTextureSize();
//texture.mShadowMargin = 5;
//var texture2 = new Texture();
//texture2.create(canvas,"../asset/texture/test2.jpg",null);
//texture2.loadTexture();
//texture2.fixSizeAsTextureSize();
//texture2.mAlpha = 0.3;
//texture2.setLevel(-1);
//var colorRect = new ColorRect();
//colorRect.create(canvas,"#ff0000");
//colorRect.setLevel(100);
//colorRect.setPosition(10,10);
//colorRect.setSize(100 , 30);
//colorRect.setVisible(false);
var label = new Label();
label.create(canvas, "123");
label.setLevel(1000);
label.setPosition(20, 20);
