/**
 * Created by jiangyuke on 2016/2/29.
 */
var MG_TYPE = {
    MSG_RQL_LOGIN: 0,
    MSG_RQL_REGISTER: 1,
    MSG_RQL_SET_MOTTO: 2,
    MSG_RQL_GET_MOTTO: 3,
    MSG_RQL_MARK: 4,
    MSG_RQL_CANCEL_MARK: 5,
    MSG_RQL_MARKED: 6,
    MSG_RQL_MARK_LIST: 7,
    MSG_RQL_ADD_DOCUMENT: 8,
    MSG_RQL_GET_DOCUMENT: 9,
    MSG_RQL_GET_DOCUMENT_LIST: 10,
    MSG_RQL_GET_DOCUMENT_LIST_BY_TYPE: 11,
    MSG_RQL_GET_DOCUMENT_LIST_SIZE: 12,
    MSG_RQL_GET_DOCUMENT_LIST_BY_TYPE_SIZE: 13,
    MSG_RQL_ADD_DOCUMENT_READER: 14,
    MSG_RQL_REPLAY_ONE_DOCUMENT: 15,
    MSG_RQL_GET_MESSAGE_LIST: 16,
    MSG_RQL_GET_MESSAGE: 17,
    MSG_RQL_MARK_MESSAGE_AS_READ: 18,
    MSG_RQL_SEND_MESSAGE: 19,
    MSG_RQL_READ_ALL_MESSAGE: 20,
    MSG_RQL_REMOVE_MESSAGE: 21,
    MSG_RQL_REMOVE_ALL_MESSAGE: 22,
    MSG_RQL_CHECK_UPLOAD_IMAGE_ACCESS: 23,
    MSG_RQL_UPLOAD_IMAGE: 24,
    MSG_RQL_GET_IMAGE: 25

}